### ISSUE TITLE
Are you going to update the readme/description?

### ISSUE THREAD

**Issue by DataFighter** [darkain/altaform-core#1]
There really isn't a description as to what this codebase does. Or where to begin. Even a short introduction would be a massive help .

**Comment by DataFighter** [comment]
Best thing RN is to follow the commit history.

**Comment by darkain** [comment]
This library needs some serious cleanup before documentation can even begin. I don't have a time line for this yet because the other repositories currently take priority (such as PUDL, which this relies heavily upon)
